name: nafsia_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Application versioning
version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

# Dependencies
dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.7
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  faker: ^2.2.0
  firebase_auth: ^5.5.1
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  flutter_material_pickers: ^3.7.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  image_picker: ^1.1.2
  intl: 0.19.0
  loading_animation_widget: ^1.3.0
  modal_progress_hud_nsn: ^0.5.1
  pretty_dio_logger: ^1.4.0
  quickalert: ^1.1.0
  shared_preferences: ^2.5.3
  skeletonizer: ^1.4.3
  timeago: ^3.7.0
  timezone: ^0.10.1
  uuid: ^4.5.1
  zego_uikit_prebuilt_call: ^4.16.29
  zego_uikit_signaling_plugin: ^2.8.12
  zego_zimkit: ^1.18.17
dev_dhmilependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# Flutter settings
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: app_images.dart
